### ISSUE TITLE
stream version 3.2.1

### ISSUE THREAD

**Issue by mizie** [IBMStreams/streamsx.dps#11]
Hi

Is this toolkit compatible with InfoSphere Stream version 3.2.1? 

while compile, i get below error

Building main composite: DpsTest1 using build configuration: Distributed

/opt/ibm/InfoSphereStreams/bin/sc -M DpsTest1 --output-directory=output/DpsTest1/Distributed --data-directory=data -t /opt/ibm/InfoSphereStreams/toolkits/com.ibm.streamsx.dps_1.0.7: --no-toolkit-indexing --no-mixed-mode-preprocessing 

Checking the constraints.
Creating the types.
Creating the functions.
Creating the operators.
Creating the processing elements.
Creating the application model.
Building the binaries.
 [CXX-function] <default_namespace>::displayHBaseTableRows
 [CXX-type] tuple<int8 a>
 [CXX-type] enum{WindowMarker,FinalMarker}
 [CXX-type] tuple<rstring potusName,rstring spouseName,rstring birthS...ffice,rstring party>
 [CXX-type] tuple<boolean fun,list<int32> joy>
 [CXX-type] tuple<int8 dummy>
 [CXX-operator] Sink1.Beat
 [CXX-operator] Sink1.NextBeat
 [CXX-operator] Sink1.Sink2
 [CXX-operator] Sink2.Sink1.Src
 [CXX-operator] Sink2.Sink1.Sink
 [CXX-operator] Sink3.Src
 [CXX-operator] Sink3.MyPerfSink
 [CXX-operator] Sink4.RunCommandSink/usr/bin/ld:/opt/ibm/InfoSphereStreams/toolkits/com.ibm.streamsx.dps_1.0.7/impl/lib/x86_64.RHEL6/libmemcached.so: file format not recognized; treating as linker script

/usr/bin/ld:/opt/ibm/InfoSphereStreams/toolkits/com.ibm.streamsx.dps_1.0.7/impl/lib/x86_64.RHEL6/libmemcached.so:1: syntax error [CXX-pe] pe DpsTest1-a

 [CXX-pe] pe DpsTest1-b
collect2: ld returned 1 exit status
 [CXX-pe] pe DpsTest1-c
make: **\* [bin/DpsTest1-b.dpe] Error 1
make: **\* Waiting for unfinished jobs....
 [CXX-pe] pe DpsTest1-d
CDISP0141E ERROR: The compilation of the generated code failed.
 [CXX-pe] pe DpsTest1-e
 [CXX-pe] pe DpsTest1-f
 [CXX-pe] pe DpsTest1-g
 [CXX-pe] pe DpsTest1-h
 [LD-pe] pe DpsTest1-a
 [LD-pe] pe DpsTest1-b

---- SPL Build for project TestDPS completed in 33.659 seconds ----

**Comment by nysenthil** [comment]
Hi AHmad,
1) Please download the Distributed Process Store (DPS) 1.0.9 for Streams 3.x from the releases section of this toolkit in our github: https://github.com/IBMStreams/streamsx.dps/releases

2) What is your Linux version? This version of the DPS toolkit is supported only on RHEL6 and CentOS6.

All the very best.

**Comment by mizie** [comment]
Hi nysenthil

I'm using RHEL 6.6 and Infosphere stream version 3.2.1

**Comment by nysenthil** [comment]
Hi Ahmad,
You can use DPS version 1.0.9 for Streams 3.x running on RHEL 6.6.

**Comment by mizie** [comment]
Hi nysenthil

I'm still received the same error when i'm running ./build-distributed.sh script under the sample directory.  I'm using Stream 3.2.1 on linux RHEL 6.6. any packages that i missed ? 

/usr/bin/ld:/opt/ibm/InfoSphereStreams/toolkits/com.ibm.streamsx.dps/impl/bin/../lib/x86_64.RHEL6/libmemcached.so: file format not recognized; treating as linker script
/usr/bin/ld:/opt/ibm/InfoSphereStreams/toolkits/com.ibm.streamsx.dps/impl/bin/../lib/x86_64.RHEL6/libmemcached.so:1: syntax error
collect2: ld returned 1 exit status
make: **\* [bin/DpsTest1-b.dpe] Error 1
make: **\* Waiting for unfinished jobs....
CDISP0141E ERROR: The compilation of the generated code failed.

**Comment by nysenthil** [comment]
Hi Ahmad,
You are getting an error message about file format being wrong. I assume you are running it on a 64 bit x86 machine. Could it be a file corruption on your disk? That error indicates something wrong with the libmemcached,so file. You may want to install the DPS toolkit in some other directory such as your home directory and try to compile the example application.

**Comment by mizie** [comment]
hi Nysenthil

I think i need to recompile all the so files again, the so files came with the download source code seem corrupted, most of the files size only 1KB. After replace the libmemcached.so, i'm getting other error, then i apply the same step on libhiredis.so and now i'm getting other error on libcrypto.so.

i tried to ran mk script, the script ran successfully but i don't seem that the script replacing the so files in the lib folder. Could you share me the so files that tested working?

your assistance is greatly appreciate

/usr/bin/ld:/opt/ibm/InfoSphereStreams/toolkits/com.ibm.streamsx.dps/impl/bin/../lib/x86_64.RHEL6/libcrypto.so: file format not recognized; treating as linker script
/usr/bin/ld:/opt/ibm/InfoSphereStreams/toolkits/com.ibm.streamsx.dps/impl/bin/../lib/x86_64.RHEL6/libcrypto.so:1: syntax error
collect2: ld returned 1 exit status

**Comment by nysenthil** [comment]
Hi Ahmad,
It is not clear why you are getting 1KB size for the .so files. I did a download of the DPS toolkit a few minutes ago (https://github.com/IBMStreams/streamsx.dps/archive/v1.0.9.tar.gz) and unzipped it to verify the file size of the impl/lib/x86_64.RHEL6. They all look fine. Could you please download the toolkit again to your Windows or Mac machine, unzip there and verify the file size of those .so files?

**Comment by mizie** [comment]
Hi Nysenthil

Now i can run the sample job, thank for your support. the mistake that i did was I extract the zip in windows then upload to my redhat machine. the correct way is to extract the zip file direct in the linux machine.

**Comment by nysenthil** [comment]
Hi Ahmad,
Fantastic. Thanks for your patience and persistence in getting it working. For our records, could you please tell which organization or company your are part of? Enjoy IBM Streams.

**Comment by mizie** [comment]
Hi Nysenthil

I'm working in Malaysia Telco company name Celcom. I'm using Infosphere Streams 3.2.1, we have used IBM Streams since version 2.0, ideally for reading CDR and support campaign purposes.
