### ISSUE TITLE
Issue using DPS toolkit on CentoOS 7

### ISSUE THREAD

**Issue by hardeys** [IBMStreams/streamsx.dps#17]
I am using DPS toolkit with Redis. When I try to compile my code, get the following errors -

/usr/bin/ld: cannot find -lcrypto
/usr/bin/ld: cannot find -lssl
/usr/bin/ld: cannot find -lldap_r
collect2: error: ld returned 1 exit status
make: **\* [bin/com.dimensiondata.raceanalytics.RaceAnalytics-b.dpe] Error 1
make: **\* Waiting for unfinished jobs....
CDISP0141E ERROR: The compilation of the generated code failed.d.

**Comment by nysenthil** [comment]
Hi Hardeep,
You will get that error if you are using the DPS toolkit shipped with the IBM Streams 4.1 product. In that case, you are required to first install openssl_devel and lcrypto libraries in your Linux OS. That is a prerequisite for using the DPS toolkit available in the Streams product.
