### ISSUE TITLE
DPS toolkit does not work with latest stable Redis version, which is 3.2.0

### ISSUE THREAD

**Issue by m-kotowski** [IBMStreams/streamsx.dps#20]
PE terminates with exception during first DPS function call.

**Comment by nysenthil** [comment]
Hi Michael,
I see that you are starting the redis-server without specifying a configuration file in the command line. When I tried running my redis 3.2.0 server like that, I also got the same error you reported. I have no idea what redis does when you don't specify a redis configuration file while starting it. When I started the redis 3.2.0 server with a proper redis.conf file, everything worked fine. Please try starting your redis 3.2.0 server with a redis.conf file and see if that will resolve your problem.

Regards,
Senthil.
