### ISSUE TITLE
SPLDOC toolkit overview refers to a figure but none is shown.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.dps#26]
http://ibmstreams.github.io/streamsx.dps/com.ibm.streamsx.dps/doc/spldoc/html/index.html

**Conceptual Overview**

The following diagram provides a conceptual overview of the interaction between the Streams application,

**Comment by nysenthil** [comment]
Hi Dan,
That missing diagram should be the one that is shown in this Streams Knowledge Center page: 
http://tinyurl.com/z9fof37

**Comment by brandtol** [comment]
In the latest version of the IO pages, the image is included 
http://ibmstreams.github.io/streamsx.dps/com.ibm.streamsx.dps/doc/en_US/spldoc/html/index.html
