### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by fangzheng** [IBMStreams/streamsx.dps#30]
In RedisDBLayer.cpp, memory for keys and values is allocated with malloc(), but is then deallocated in DistributedProcessStore.h with delete[]. This mismatch could cause memory leak or undefined behaviors.

The same mismatch exists in other *DBLayer.cpp as well. It would be nice to replace delete[] with free() in DistributedProcessStore.h.

**Comment by brandtol** [comment]
This is solved with release v3.1.0 ( #39)
