### ISSUE TITLE
Question: Redis with authentication?

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.dps#31]
Does DPS support the case where the Redis server requires authentication?

I couldn't see anything obvious in the SPLDOC.

**Comment by ddebrunner** [comment]
Basically the `-a` option to redis-cli.

Or is a Redis URI supported, which includes the password: `redis::/user:XXXXXX@hostname:port`?

Trying to use DPS against a Redis instance on Bluemix (Compose service).

**Comment by nysenthil** [comment]
Hi Dan,
There is no authentication support inside the DPS for Redis at this time. But, we have done it for the IBM HSA KVS back-end. We will do a similar thing for Redis very soon. There will also be encryption support added soon by the Berlin team (dpsPutEncrypted, dpsGetEncrypted).

**Comment by mikespicer** [comment]
@nysenthil Did you have a plan in mind for how to add authentication and SSL connectivity for Redis or was simply a known requirement that had not been given any thought yet?

**Comment by nysenthil** [comment]
Hi Mike: I added Redis authentication (password) support in the 3rd quarter of 2017 for Redis based on an urgent need for that from couple of our customers. But, never thought about adding SSL support.
