### ISSUE TITLE
Add support for Redis on the cloud

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.dps#38]
The toolkit cannot be used in Bluemix with Redis on the cloud because the authentication is missing as per these instructions: https://redislabs.com/lp/hiredis/

**Comment by brandtol** [comment]
This will be solved with Senthil's next changeset.

**Comment by brandtol** [comment]
With these additional changes (pull req #49) two of the samples can be run on Bluemix. A quick guide to run one sample is in the wiki pages 
[Run samples on Bluemix](https://github.com/IBMStreams/streamsx.dps/wiki/Run-DPS-samples-in-Bluemix)
