### ISSUE TITLE
Use Gitflow for the DPS repository ?

### ISSUE THREAD

**Issue by brandtol** [IBMStreams/streamsx.dps#40]
Shall we adopt the Gitflow process for DPS ? It is used by
other toolkits like health and kafka as well, and looks pretty reasonable to me. 

Description is here : http://nvie.com/posts/a-successful-git-branching-model
In a nutshell it means that the master branch is reserved for releases, all
development is done on the "develop" branch through the use of feature branches. 

Please object, if you think this is not suitable for DPS.

If you use the Eclipse Egit plugin, additional functions for gitflow can be installed 
from the Egit site, module : "Git integration for Eclipse - Gitflow support" : 
http://eclipsesource.com/blogs/2015/06/22/git-flow-top-eclipse-mars-feature-3

**Comment by nysenthil** [comment]
Hi Oliver,
That is a very useful thing to do. Let us plan to use the Gitflow for DPS. We will discuss more in our teleconference on Thursday.

**Comment by chanskw** [comment]
+1

We use it with hubflow command line tool, in combination of EGit.  So far, I find the command line tool better.  Here's a link for tooling:
https://datasift.github.io/gitflow/GitFlowForGitHub.html

**Comment by brandtol** [comment]
@chanskw hubflow looks fine! Maybe we should create a wiki page in the administration project that gathers information on gitflow+tools, so toolkits that decide to use it can link to the page.
If this is not covered elsewhere so far ....

Regarding DPS : can you switch the default branch to develop in the settings dialog ? I noticed that the commiters for DPS do not have admin rights, so we cannot access the settings.

**Comment by chanskw** [comment]
Yes... just let me know your decision and when to change the default branch to develop... I will make a change then.

**Comment by chanskw** [comment]
I also agree to creating a wiki page.  Just haven't had time to do that.

**Comment by brandtol** [comment]
I discussed with Senthil, and we think switch to develop branch as default can be done now. Nobody objected so far...
