### ISSUE TITLE
Update SPLDoc for 3.1.0

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.dps#43]
This may already be in the works since the release happened on Friday, but the SPLDoc should be updated to reflect the latest toolkit release.

**Comment by brandtol** [comment]
@Alex-Cook4 I updated the [gh-pages](http://ibmstreams.github.io/streamsx.dps/releases.html)
Maybe I missed something. Can you check and close the issue if it looks ok.

**Comment by Alex-Cook4** [comment]
Thanks @brandtol!
