### ISSUE TITLE
DPS toolkit does not build on CentOS 6.x

### ISSUE THREAD

**Issue by brandtol** [IBMStreams/streamsx.dps#45]
If /etc/redhat-release contains the string "CentOS ...." as in the Streams Quickstart edition,
the toolkit does not build. If the string is like "Red Hat Enterprise ...." it works. Probably some Makefile needs adaption.

**Comment by brandtol** [comment]
The ../dependencies/platform-info.pl script only detects RedHat 6 Santiago and RedHat 7 Maipo versions. Centos versions are named Final (centos 6) and Core (centos 7). 

We can adapt the script to output a warning if Centos is detected, and return RHEL as OS identifier.

**Comment by nysenthil** [comment]
Oliver,
As you suspected yesterday, it is in the build script. Great. Please go ahead and fix it. We will always have  customers on CentOS6 and CentOS7. Our Streams QSE itself is still on CentOS6 at this time.

**Comment by brandtol** [comment]
Fixed with this commit: https://github.com/IBMStreams/streamsx.dps/commit/4eb38b35923ba18c512d74827a244084d9c5332a
