### ISSUE TITLE
Provide and test script to update gh-pages

### ISSUE THREAD

**Issue by brandtol** [IBMStreams/streamsx.dps#46]
A script to update the documentation webpages needs to be added, and tested. It can be copied from the inet toolkit and adapted for DPS needs. Open questions:
- shall we keep documentation for older versions in the gh-pages branch by creating new directories for each new release. Or is there a mechanism with tags on gh-pages branch available ?
- shall we try to maintain gh-pages documentation for the develop branch ?

**Comment by brandtol** [comment]
Some regulations:
- gh-pages will be updated only on release (master branch), no updates for develop branch
- for each new version there will be a folder with the version number in the doc dir. Example : .../com.ibm.streamsx.dps/doc/v3.2.0 where the en_US and the icons folders will be copied
- instead of providing a script, the necessary changes will be documented

**Comment by anouri** [comment]
- DPS SPD doc upgraded.
- DPS gh-pages and broken links fixed.
