### ISSUE TITLE
README.md needs to be updated

### ISSUE THREAD

**Issue by p6arora** [IBMStreams/streamsx.dps#63]
In the readme, it states:

> "There are plenty of details available about the installation, configuration, API description, built-in example etc. Please refer to the com.ibm.streamsx.dps/doc/dps-usage-tips.txt file for getting a good start in using this toolkit."

The toolkit does not contain the dps-usage-tips.txt file. It was removed in a previous update

**Comment by brandtol** [comment]
I will update the README accordingly. The info from dps-usage-tips.txt will go into the Wiki pages after some rework.

**Comment by brandtol** [comment]
done
