### ISSUE TITLE
Create "tests" directory? 

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.dps#65]
I would like to add some Python topology unittests of the DpsTTL convenience composites. Would it be ok for me to place them in a new parent directory: `tests/dpsTTLWithReconnect` 

Let me know if there is a different preference.

**Comment by brandtol** [comment]
This looks fine, please go ahead.
If possible please add a build.xml in the tests directory with a target named test that does whatever is needed to run the tests and fails if appropriate. This makes it easier to include the suite in automatic regression in the future.
