### ISSUE TITLE
Add new API method to set the configuration without using a file

### ISSUE THREAD

**Issue by brandtol** [IBMStreams/streamsx.dps#66]
**Current situation**

The DPS server configuration is read from a file with the default path etc/no-sql-kv-servers.cfg.
To change the server configuration without recompiling the application, one could put this file somewhere
on a shared/local storage and change its location via the dpsSetConfigFile() method. Than stopping the application, changing the config file manually and restarting the application would be sufficient. 
However, this may not be suitable for environments where no common file system is available, like cloud environments.

**Proposed enhancement**

We should add a method that allows an application to set the configuration for example by evaluating
submission time parameters or using the SPL getApplicationConfig... methods, to get the needed values.
The new method should be usable from SPL, C++ and Java primitive operators.

A method to pass the configuration as string using the same format as the configuration file would be sufficient:
`boolean dpsSetConfigString(rstring configData)`
or
`boolean dpsSetConfigString(list<rstring> configDataLines)`

**Comment by anouri** [comment]
already corrected
