### ISSUE TITLE
Add example to DpsRunDataStore command

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.dps#69]
I had a new Streams developer struggle a bit with the new list<rstring> option for the new DpsRunDataStore command. They requested that we add an example to the docs. 

Here is the example I showed them: 
```
		mutable rstring result = ""; 
		mutable list<rstring> cmd = ["rpush" , "key", jsonString]; 
		mutable uint64 error = 0; 
		dpsRunDataStoreCommand(cmd, result, error);
```

**Comment by nysenthil** [comment]
Please ask that developer to do a search for dpsRunDataStoreCommand in the following file available in the DPS toolkit. It shows 15 different ways of using that API with different Redis commands.

streamsx.dps-master/samples/advanced/04_all_dps_apis_at_work_in_spl/com.acme.test/Main.splmm
