### ISSUE TITLE
Gather requirements for Cloudant access

### ISSUE THREAD

**Issue by brandtol** [IBMStreams/streamsx.dps#73]
This issue is used to gather new requirements for CLoudant access.
 
1) It should be possible to use the _changes API to  get a list of recent changes for a database.
https://console.bluemix.net/docs/services/Cloudant/api/database.html#get-changes

**Comment by kocolosk** [comment]
Yes I think that's the main one. If you drill down on the _changes topic you'll find a number of additional points which are covered in the documentation:

- Each element of the _changes feed includes a sequence token that allows the feed to be resumed from that point if the connection is interrupted. This requires that Streams store the last seen token somewhere.
- The feed can be configured to keep an open socket and continuously deliver new updates.
- The feed can optionally include the full document bodies. By default it only delivers some minimal document metadata (_id and a list of current revisions)

**Comment by brandtol** [comment]
Closing this issue, as the streamsx.cloudant toolkit will handle this.
