### ISSUE TITLE
Samples in the advanced folder are the same as existing cpp and Java samples.

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.dps#74]
The DPSUsageFromxx samples are based on the 0x_using samples, which is why they have similar names.
They are just pared down and added extra things like copyrights. So there is no need for them to also be included in the advanced folder.

In addition, the DPSAux operator is required for the 01_cpp sample to work in certain situations but it isn't present.

**Comment by brandtol** [comment]
Yes, samples should be reorganized, to have them all on the top level. Without duplicated functionallity.

**Comment by anouri** [comment]
no demand for long time
