### ISSUE TITLE
 Improve Java samples to build with Makefile and Studio

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.dps#76]
At this line: https://github.com/IBMStreams/streamsx.dps/blob/master/samples/DPSUsageFromJava/impl/java/src/application/DataStoreTester.java#L38

Changing the Java samples to use the dps-helper lib within impl/lib causes a problem if  you are using Streams Studio, because the Makefile is not used to build the project.
So after importing the project into studio and following the instructions to build in the README, the project still fails to build.
So I suggest that we change the sample to be flexible for both building options (Makefile/Studio) or update the instructions in the README.

**Comment by brandtol** [comment]
With the 3.3.0 release I updates the README for the Java sample. The Studio project settings now invoke the sample makefile as external builder, instead of using the internal studio builder. The external makefile takes care of copying the dps-helper to impl/lib.
