### ISSUE TITLE
Unable to connect to cloud service 'Compose for Redis'

### ISSUE THREAD

**Issue by siegenth** [IBMStreams/streamsx.dps#79]
I'm unable to communicate with the "Compose for Redis"  service using the provided example  "DPSUsageFromSPL.spl". Possible issue interpreting the connection string. 

**I can communicate the Redis service using redis-cli:**
```
$ src/redis-cli -h sl-us-south-1-portal.22.dblayer.com -p 43926 -a REXIEBHDEGTTBMYX
sl-us-south-1-portal.22.dblayer.com:43926> set fred "frequently ridiculous educational device"
OK
sl-us-south-1-portal.22.dblayer.com:43926> get fred
"frequently ridiculus educational device"
sl-us-south-1-portal.22.dblayer.com:43926> 
```

**The "no-sql-kv-store-servers.cfg" looks like:**
```
#
redis
sl-us-south-1-portal.22.dblayer.com:43926:REXIEBHDEGTTBMYX
```

**I get this error.** 

```
Job[7], PE[7], Message[CDISR5030E]:
An exception occurred during the execution of the TaxiDataSink operator. The exception is: Invalid NoSQL store product name is specified in the configuration file: sl-us-south-1-portal.22.dblayer.com:43926:rexiebhdegttbmyx#
```

Notes:
1) I tried 'redis-cluster' as well. 
2) Built a new version of the toolkit per instructions. 
3) Attempt  from  standalone and by submitting to the cloud
4) I created the Redis Service after June 1, I had to upgrade my internal IBM account. (?Possible change to the Redis service?)
5) I created the service with TLS and without. 
6) The connection information has been obfuscated.

**Comment by brandtol** [comment]
Can you check if there is a problem with line endings in the config file (dos2unix or so) ?

**Comment by anouri** [comment]
It is a duplicate to issue:
Add support for Redis over TLS #78
We have planned to implement support TLS for Redis in the next release.
