### ISSUE TITLE
DPS functions and inet toolkit java functions don't work well inside a single operator

### ISSUE THREAD

**Issue by nysenthil** [IBMStreams/streamsx.dps#84]
I worked with a customer today and their code has a Custom operator in which they are doing a call to dpsHas immediately followed by call to the inet toolkit's httpGet function. It compiles fine with the DPS toolkit version v3.3.3. But, when they launch the application, it simply doesn't perform anything. DPS logs say it read the redis server configuration from the DPS config file. After that, it goes silent without even attempting to connect to the Redis server. I they comment out the line that calls the httpGet Java function, then their logic works fine. This needs to investigated and fixed.

As a workaround, I tried with the customer to move the logic that makes the call to the httpGet to on its own operator. That worked fine. However, we need to fix the problem described above.

**Comment by brandtol** [comment]
Not sure which functions they use, but in iet toolkit there are also c++ http functions : https://github.com/IBMStreams/streamsx.inet/blob/master/com.ibm.streamsx.inet/impl/include/httpFunctions.h

These use libcurl and may conflict with DPSs own libdurl. See issue #16 

On the other hand, I think DPS loads libcurl only when used with cloudant, not for Redis (not sure).

**Comment by anouri** [comment]
corrected
