### ISSUE TITLE
AT compiler check - move fix path setting

### ISSUE THREAD

**Issue by streams-toolkits** [IBMStreams/streamsx.dps#88]
The ppc64 & ppc64le machines recommend to use AT compiler, but the fix path setting is not good way to specify the compiler path. It should be set by a CXX variable or by the PATH.

**Comment by markheger** [comment]
com.ibm.streamsx.dps/impl/Makefile has commented the ppc specific part and AT compiler is not hard coded with a fixed path, but `ppcenv.sh` contains hard-coded path settings to AT compiler.

**Comment by anouri** [comment]
The Makefile of streamsx.dps has to be corrected.
https://github.com/IBMStreams/streamsx.dps/blob/master/Makefile

**Comment by ZollnaPa** [comment]
The Makefile includes the target 'check-compiler' but it is removed from 'all' target. If needed, the user must make an explicit call of the 'check-complier' target. 
```
all: check-streams gen-message ${SUBDIRS:%=%.all}
```

**Comment by markheger** [comment]
@ZollnaPa can this issue be closed? or is something missing?

**Comment by nysenthil** [comment]
Hi Mark,
It is not clear how  many customers are running IBM Streams on PPC. It all depends on that factor if we have a need to keep supporting the newer versions of the DPS toolkit in the PPC environment.

**Comment by markheger** [comment]
It is more a question about have settings in Makefile or outside Makefile, rather than support or not, if I understand the issue correctly.

**Comment by streams-toolkits** [comment]
The ant files provide workaround. There is no impact on customer builds.
